# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-10 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='on_created',
            new_name='created_on',
        ),
    ]
